"use client";
import { motion } from "motion/react";
import { activity } from "@/data/content";
import { useMemo } from "react";

// Import Obsidian-synced heatmap data (generated by scripts/sync-obsidian.ts)
let obsidianData: { weeks: { date: string; level: number }[][] } | null = null;
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  obsidianData = require("@/data/heatmap-data.json");
} catch {
  // No synced data yet — will use simulated fallback
}

const tagColors: Record<string, string> = {
  web: "bg-blue-500/20 text-blue-400",
  design: "bg-purple-500/20 text-purple-400",
  infra: "bg-amber-500/20 text-amber-400",
  agent: "bg-cyan-500/20 text-cyan-400",
  quant: "bg-green-500/20 text-green-400",
  tooling: "bg-orange-500/20 text-orange-400",
  crypto: "bg-red-500/20 text-red-400",
  trading: "bg-red-500/20 text-red-400",
  ml: "bg-violet-500/20 text-violet-400",
  hft: "bg-pink-500/20 text-pink-400",
  macro: "bg-yellow-500/20 text-yellow-400",
  research: "bg-teal-500/20 text-teal-400",
  options: "bg-emerald-500/20 text-emerald-400",
  poker: "bg-blue-500/20 text-blue-400",
  community: "bg-indigo-500/20 text-indigo-400",
};

// Generate heatmap data for the last 12 weeks
// Merges: Obsidian daily notes (synced JSON) + activity feed entries + simulated fallback
function Heatmap() {
  const weeks = useMemo(() => {
    // Build Obsidian lookup if data is available
    const obsidianLookup = new Map<string, number>();
    if (obsidianData?.weeks) {
      for (const week of obsidianData.weeks) {
        for (const day of week) {
          if (day.level > 0) obsidianLookup.set(day.date, day.level);
        }
      }
    }

    const data: number[][] = [];
    const feedDates = new Set(activity.feed.map((f) => f.date));
    const today = new Date("2026-03-07");

    for (let w = 11; w >= 0; w--) {
      const week: number[] = [];
      for (let d = 0; d < 7; d++) {
        const date = new Date(today);
        date.setDate(date.getDate() - w * 7 - (6 - d));
        const dateStr = date.toISOString().split("T")[0];

        // Priority: Obsidian data > feed data > simulated
        const obsLevel = obsidianLookup.get(dateStr) ?? 0;
        const feedCount = activity.feed.filter((f) => f.date === dateStr).length;
        const feedLevel = feedCount > 0 ? Math.min(feedCount + 1, 4) : 0;

        if (obsLevel > 0 || feedLevel > 0) {
          week.push(Math.min(4, Math.max(obsLevel, feedLevel)));
        } else {
          // Simulated fallback: more recent = more likely active
          const recency = 1 - w / 12;
          const rand = Math.random();
          if (rand < recency * 0.4) week.push(Math.ceil(Math.random() * 3));
          else week.push(0);
        }
      }
      data.push(week);
    }
    return data;
  }, []);

  const levelColors = [
    "bg-zinc-900",           // 0 - no activity
    "bg-green-900/40",       // 1 - low
    "bg-green-700/50",       // 2 - medium
    "bg-green-500/60",       // 3 - high
    "bg-green-400/70",       // 4 - very high
  ];

  return (
    <div className="flex gap-[3px]">
      {weeks.map((week, wi) => (
        <div key={wi} className="flex flex-col gap-[3px]">
          {week.map((level, di) => (
            <motion.div
              key={`${wi}-${di}`}
              initial={{ opacity: 0, scale: 0 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: wi * 0.03 + di * 0.01, duration: 0.3 }}
              className={`h-[11px] w-[11px] rounded-[2px] ${levelColors[level]} transition-colors hover:ring-1 hover:ring-white/20`}
            />
          ))}
        </div>
      ))}
    </div>
  );
}

export function Activity() {
  return (
    <section id="activity" className="relative px-4 py-24 md:py-32">
      <div className="mx-auto max-w-5xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-12"
        >
          <h2 className="text-3xl font-bold text-neutral-200 md:text-4xl">
            {activity.heading}
          </h2>
          <p className="mt-2 text-neutral-500">{activity.subtitle}</p>
        </motion.div>

        {/* Heatmap */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="mb-12 overflow-x-auto rounded-xl border border-white/[0.06] bg-zinc-950/50 p-6"
        >
          <div className="mb-3 flex items-center justify-between">
            <span className="font-mono text-xs text-neutral-500">12 weeks of activity</span>
            <div className="flex items-center gap-1.5">
              <span className="text-[10px] text-neutral-600">Less</span>
              {[0, 1, 2, 3, 4].map((l) => (
                <div
                  key={l}
                  className={`h-[10px] w-[10px] rounded-[2px] ${
                    ["bg-zinc-900", "bg-green-900/40", "bg-green-700/50", "bg-green-500/60", "bg-green-400/70"][l]
                  }`}
                />
              ))}
              <span className="text-[10px] text-neutral-600">More</span>
            </div>
          </div>
          <Heatmap />
        </motion.div>

        {/* Activity feed */}
        <div className="relative">
          {/* Timeline line */}
          <div className="absolute left-[7px] top-0 h-full w-px bg-gradient-to-b from-green-500/30 via-zinc-800 to-transparent" />

          <div className="space-y-6">
            {activity.feed.map((item, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -10 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.4, delay: i * 0.05 }}
                className="flex gap-4"
              >
                {/* Dot */}
                <div className="relative mt-1.5 flex-shrink-0">
                  <div className="h-[15px] w-[15px] rounded-full border-2 border-zinc-800 bg-zinc-950">
                    <div className="m-auto mt-[2.5px] h-[6px] w-[6px] rounded-full bg-green-500/60" />
                  </div>
                </div>

                {/* Content */}
                <div className="flex-1 pb-2">
                  <div className="flex items-baseline gap-2">
                    <span className="font-mono text-[10px] text-neutral-600">{item.date}</span>
                  </div>
                  <h4 className="mt-0.5 text-sm font-medium text-neutral-200">{item.title}</h4>
                  <p className="mt-1 text-xs leading-relaxed text-neutral-500">{item.description}</p>
                  <div className="mt-2 flex gap-1.5">
                    {item.tags.map((tag) => (
                      <span
                        key={tag}
                        className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${tagColors[tag] || "bg-zinc-800 text-neutral-500"}`}
                      >
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
