"use client";
import { motion } from "motion/react";

// Import digest data (generated by scripts/daily-digest.sh)
let digestData: {
  generated: string;
  date: string;
  skills: { modified: number; files: string[] };
  commits: { count: number; recent: string[] };
  heatmap: { activeDays: number; obsidianFiles: number; claudeFiles: number; gitDays: number };
  highlights: string[];
} | null = null;

try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  digestData = require("@/data/digest.json");
} catch {
  // No digest data yet
}

const categoryIcons: Record<string, string> = {
  finance: "💹",
  poker: "🃏",
  frontend: "🎨",
  devops: "⚙️",
  default: "📄",
};

function getCategoryIcon(file: string): string {
  for (const [key, icon] of Object.entries(categoryIcons)) {
    if (file.startsWith(key)) return icon;
  }
  return categoryIcons.default;
}

function timeAgo(dateStr: string): string {
  const diff = Date.now() - new Date(dateStr).getTime();
  const hours = Math.floor(diff / (1000 * 60 * 60));
  if (hours < 1) return "just now";
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  return `${days}d ago`;
}

export function Digest() {
  if (!digestData) return null;

  const { date, skills, commits, heatmap, highlights, generated } = digestData;

  return (
    <section id="digest" className="relative px-4 py-24 md:py-32">
      <div className="mx-auto max-w-5xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="mb-10"
        >
          <div className="flex items-center gap-3">
            <h2 className="text-3xl font-bold text-neutral-200 md:text-4xl">
              Claude Digest
            </h2>
            <span className="rounded-full border border-green-500/30 bg-green-500/10 px-2.5 py-0.5 text-xs font-medium text-green-400">
              {timeAgo(generated)}
            </span>
          </div>
          <p className="mt-2 text-neutral-500">
            What I learned and built — auto-synced daily.
          </p>
        </motion.div>

        {/* Stats Bar */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="mb-8 grid grid-cols-2 gap-3 md:grid-cols-4"
        >
          {[
            { label: "Skills Updated", value: skills.modified, color: "text-violet-400", border: "border-violet-500/20" },
            { label: "Git Commits", value: commits.count, color: "text-green-400", border: "border-green-500/20" },
            { label: "Active Days", value: heatmap.activeDays, color: "text-yellow-400", border: "border-yellow-500/20" },
            { label: "Memory Files", value: heatmap.claudeFiles, color: "text-blue-400", border: "border-blue-500/20" },
          ].map((stat, i) => (
            <motion.div
              key={stat.label}
              initial={{ opacity: 0, scale: 0.9 }}
              whileInView={{ opacity: 1, scale: 1 }}
              viewport={{ once: true }}
              transition={{ delay: 0.15 + i * 0.05 }}
              className={`rounded-xl border ${stat.border} bg-zinc-950/50 p-4 text-center`}
            >
              <div className={`text-2xl font-bold ${stat.color}`}>{stat.value}</div>
              <div className="mt-1 text-xs text-neutral-500">{stat.label}</div>
            </motion.div>
          ))}
        </motion.div>

        <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
          {/* Highlights */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.2 }}
            className="rounded-xl border border-white/[0.06] bg-zinc-950/50 p-5"
          >
            <h3 className="mb-4 flex items-center gap-2 text-sm font-semibold text-neutral-300">
              <span className="inline-flex h-5 w-5 items-center justify-center rounded bg-amber-500/20 text-[10px]">
                ⚡
              </span>
              Highlights
            </h3>
            <ul className="space-y-2.5">
              {highlights.map((h, i) => (
                <motion.li
                  key={i}
                  initial={{ opacity: 0, x: -10 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.3 + i * 0.05 }}
                  className="flex gap-2 text-xs leading-relaxed text-neutral-400"
                >
                  <span className="mt-1 h-1 w-1 flex-shrink-0 rounded-full bg-amber-500/60" />
                  {h}
                </motion.li>
              ))}
            </ul>
          </motion.div>

          {/* Skills Modified */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.25 }}
            className="rounded-xl border border-white/[0.06] bg-zinc-950/50 p-5"
          >
            <h3 className="mb-4 flex items-center gap-2 text-sm font-semibold text-neutral-300">
              <span className="inline-flex h-5 w-5 items-center justify-center rounded bg-violet-500/20 text-[10px]">
                📚
              </span>
              Skills Learned
            </h3>
            <div className="space-y-2">
              {skills.files.map((file, i) => (
                <motion.div
                  key={file}
                  initial={{ opacity: 0, x: -10 }}
                  whileInView={{ opacity: 1, x: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.35 + i * 0.04 }}
                  className="flex items-center gap-2 rounded-lg bg-zinc-900/50 px-3 py-1.5"
                >
                  <span className="text-xs">{getCategoryIcon(file)}</span>
                  <span className="font-mono text-xs text-neutral-400">{file}</span>
                </motion.div>
              ))}
            </div>
          </motion.div>

          {/* Recent Commits */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5, delay: 0.3 }}
            className="rounded-xl border border-white/[0.06] bg-zinc-950/50 p-5 md:col-span-2"
          >
            <h3 className="mb-4 flex items-center gap-2 text-sm font-semibold text-neutral-300">
              <span className="inline-flex h-5 w-5 items-center justify-center rounded bg-green-500/20 text-[10px]">
                🔨
              </span>
              Recent Commits
            </h3>
            <div className="space-y-1.5">
              {commits.recent.map((msg, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0 }}
                  whileInView={{ opacity: 1 }}
                  viewport={{ once: true }}
                  transition={{ delay: 0.35 + i * 0.04 }}
                  className="flex items-center gap-2 text-xs"
                >
                  <span className="h-1.5 w-1.5 flex-shrink-0 rounded-full bg-green-500/40" />
                  <span className="font-mono text-neutral-500">{msg}</span>
                </motion.div>
              ))}
            </div>
            <div className="mt-3 text-[10px] text-neutral-600">
              {date} · {commits.count} commits · auto-synced to{" "}
              <a
                href="https://github.com/RoddyH17/roddy95o-website"
                target="_blank"
                rel="noopener noreferrer"
                className="text-neutral-500 underline decoration-neutral-700 hover:text-neutral-400"
              >
                GitHub
              </a>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
