#!/bin/bash
# Daily Learning Digest — runs at noon daily via launchd
# 1. Syncs heatmap  2. Pushes to GitHub  3. Sends email  4. macOS notification
set -e
cd "$(dirname "$0")/.."

export PATH="/usr/local/bin:/usr/bin:/bin:$HOME/.nvm/versions/node/v22.17.1/bin:$PATH"
export GH_CONFIG_DIR="$HOME/gh-config"

DATE=$(date +%Y-%m-%d)
LOG="$HOME/.claude-daily-digest.log"
EMAIL="zh89@cornell.edu"

echo "[$DATE] Starting daily digest..." >> "$LOG"

# 1. Count recent skill files modified in last 24h
SKILL_DIR="$HOME/.claude/projects/-Users-roddy/memory/skills"
SKILLS_MODIFIED=$(find "$SKILL_DIR" -name "*.md" -mtime -1 2>/dev/null | wc -l | tr -d ' ')
SKILL_LIST=$(find "$SKILL_DIR" -name "*.md" -mtime -1 2>/dev/null | while read f; do
  basename "$(dirname "$f")"/"$(basename "$f" .md)"
done | sort)

# 2. Count git commits in last 24h
COMMITS=$(git log --since="24 hours ago" --oneline 2>/dev/null | wc -l | tr -d ' ')
COMMIT_LOG=$(git log --since="24 hours ago" --oneline 2>/dev/null || echo "No commits")

# 3. Count heatmap sources
CLAUDE_FILES=$(find "$SKILL_DIR" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')

# 4. Sync heatmap
SYNC_OUTPUT=$(npx tsx scripts/sync-obsidian.ts 2>&1)
echo "[$DATE] $SYNC_OUTPUT" >> "$LOG"

# 5. Build email body
BODY="━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Daily Learning Digest — $DATE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SKILL FILES MODIFIED (last 24h): $SKILLS_MODIFIED
$SKILL_LIST

GIT COMMITS (last 24h): $COMMITS
$COMMIT_LOG

HEATMAP
$SYNC_OUTPUT

WEBSITE: https://roddy95o.com
REPO: https://github.com/RoddyH17/roddy95o-website
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Auto-generated by Claude daily digest pipeline."

# 6. Build + push if there are changes
PUSHED="No"
if [[ "$SKILLS_MODIFIED" -gt 0 ]] || [[ "$COMMITS" -gt 0 ]]; then
  echo "[$DATE] Skills: $SKILLS_MODIFIED, Commits: $COMMITS" >> "$LOG"
  npm run build >> "$LOG" 2>&1

  if [[ -n $(git status --porcelain) ]]; then
    git add -A
    git commit -m "Daily digest sync: $DATE

Heatmap refreshed. Skills: $SKILLS_MODIFIED modified, Commits: $COMMITS.

Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>" >> "$LOG" 2>&1
    git push origin main >> "$LOG" 2>&1
    PUSHED="Yes"
    echo "[$DATE] Pushed to GitHub — auto-deploy triggered" >> "$LOG"
  fi
fi

# 7. Send email via macOS built-in mail (uses local sendmail/postfix)
#    Fallback: use Python's smtplib with Gmail SMTP if local mail fails
send_email() {
  # Try Python with Cornell SMTP (no auth needed for local sends on campus)
  # Fallback to macOS mail command
  python3 - "$EMAIL" "$DATE" "$BODY" <<'PYEOF'
import sys, subprocess

to_addr = sys.argv[1]
date = sys.argv[2]
body = sys.argv[3]

subject = f"[Claude Digest] Daily Learning Report — {date}"

# Construct email
msg = f"""From: Claude Daily Digest <noreply@roddy95o.com>
To: {to_addr}
Subject: {subject}
Content-Type: text/plain; charset=utf-8
MIME-Version: 1.0

{body}
"""

# Try local sendmail first
try:
    p = subprocess.run(["/usr/sbin/sendmail", "-t"], input=msg.encode(), capture_output=True, timeout=10)
    if p.returncode == 0:
        print("Email sent via sendmail")
        sys.exit(0)
except Exception:
    pass

# Fallback: write email to file for manual review
with open(f"{sys.argv[1].replace('@','_at_')}_digest_{date}.eml", "w") as f:
    f.write(msg)
print("Email saved to .eml file (sendmail unavailable)")
PYEOF
}

EMAIL_RESULT=$(send_email 2>&1)
echo "[$DATE] Email: $EMAIL_RESULT" >> "$LOG"

# 8. macOS notification
osascript -e "display notification \"Skills: ${SKILLS_MODIFIED} modified | Commits: ${COMMITS} | Pushed: ${PUSHED}\" with title \"Claude Daily Digest\" subtitle \"$DATE\" sound name \"Glass\"" 2>/dev/null || true

echo "[$DATE] Done. Notification sent." >> "$LOG"
