#!/bin/bash
# Daily Learning Digest — runs at noon daily + on boot via launchd
# 1. Syncs heatmap  2. Pushes to GitHub  3. Sends email  4. macOS notification
set -e
cd "$(dirname "$0")/.."

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$HOME/.nvm/versions/node/v22.17.1/bin:$PATH"
export GH_CONFIG_DIR="$HOME/gh-config"

DATE=$(date +%Y-%m-%d)
TIME=$(date +%H:%M)
LOG="$HOME/.claude-daily-digest.log"
EMAIL="roddyhuang17@gmail.com"

echo "" >> "$LOG"
echo "=== [$DATE $TIME] Daily Digest Starting ===" >> "$LOG"

# 1. Count recent skill files modified in last 24h
SKILL_DIR="$HOME/.claude/projects/-Users-roddy/memory/skills"
SKILLS_MODIFIED=$(find "$SKILL_DIR" -name "*.md" -mtime -1 2>/dev/null | wc -l | tr -d ' ')
SKILL_LIST=$(find "$SKILL_DIR" -name "*.md" -mtime -1 2>/dev/null | while read f; do
  rel=$(echo "$f" | sed "s|$SKILL_DIR/||")
  echo "  - $rel"
done | sort)

# 2. Count git commits in last 24h
COMMITS=$(git log --since="24 hours ago" --oneline 2>/dev/null | wc -l | tr -d ' ')
COMMIT_LOG=$(git log --since="24 hours ago" --oneline 2>/dev/null | head -10 || echo "  (none)")

# 3. Count heatmap sources
CLAUDE_FILES=$(find "$SKILL_DIR" -name "*.md" 2>/dev/null | wc -l | tr -d ' ')

# 4. Sync heatmap
SYNC_OUTPUT=$(npx tsx scripts/sync-obsidian.ts 2>&1)
echo "  Heatmap: $SYNC_OUTPUT" >> "$LOG"

# 5. Compose report
SUBJECT="[Claude Digest] $DATE — Skills: $SKILLS_MODIFIED | Commits: $COMMITS"
BODY="━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Daily Learning Digest — $DATE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📚 SKILL FILES MODIFIED (last 24h): $SKILLS_MODIFIED
$SKILL_LIST

📝 GIT COMMITS (last 24h): $COMMITS
$COMMIT_LOG

📊 HEATMAP
$SYNC_OUTPUT

🌐 WEBSITE: https://roddy95o.com
🔗 REPO: https://github.com/RoddyH17/roddy95o-website

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Auto-generated by Claude daily digest pipeline.
"

# 6. Build + push if there are changes
PUSHED="No"
if [[ "$SKILLS_MODIFIED" -gt 0 ]] || [[ "$COMMITS" -gt 0 ]]; then
  echo "  Building (Skills: $SKILLS_MODIFIED, Commits: $COMMITS)..." >> "$LOG"
  npm run build >> "$LOG" 2>&1

  if [[ -n $(git status --porcelain) ]]; then
    git add -A
    git commit -m "Daily digest sync: $DATE

Heatmap refreshed. Skills: $SKILLS_MODIFIED modified, Commits: $COMMITS.

Co-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>" >> "$LOG" 2>&1
    git push origin main >> "$LOG" 2>&1
    PUSHED="Yes"
    echo "  Pushed to GitHub — auto-deploy triggered" >> "$LOG"
  else
    echo "  No changes to push" >> "$LOG"
  fi
else
  echo "  No new activity in last 24h, skipping build" >> "$LOG"
fi

# 7. Send email via Gmail SMTP (requires App Password in ~/.gmail-app-password)
GMAIL_PASS_FILE="$HOME/.gmail-app-password"
if [[ -f "$GMAIL_PASS_FILE" ]]; then
  GMAIL_PASS=$(cat "$GMAIL_PASS_FILE" | tr -d '[:space:]')
  python3 - <<PYEOF
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

sender = "roddyhuang17@gmail.com"
password = "$GMAIL_PASS"
recipient = "$EMAIL"

msg = MIMEMultipart()
msg["From"] = "Claude Daily Digest <roddyhuang17@gmail.com>"
msg["To"] = recipient
msg["Subject"] = """$SUBJECT"""
msg.attach(MIMEText("""$BODY""", "plain", "utf-8"))

try:
    with smtplib.SMTP("smtp.gmail.com", 587, timeout=15) as s:
        s.starttls()
        s.login(sender, password)
        s.send_message(msg)
    print("Email sent via Gmail SMTP")
except Exception as e:
    print(f"Email failed: {e}")
PYEOF
  EMAIL_RESULT=$?
  echo "  Email: sent to $EMAIL" >> "$LOG"
else
  echo "  Email: SKIPPED — no ~/.gmail-app-password file found" >> "$LOG"
  echo "  Create it: echo 'your-16-char-app-password' > ~/.gmail-app-password && chmod 600 ~/.gmail-app-password" >> "$LOG"
fi

# 8. macOS notification via terminal-notifier (works in launchd context)
NOTIF_MSG="Skills: ${SKILLS_MODIFIED} modified | Commits: ${COMMITS} | Pushed: ${PUSHED}"
if command -v terminal-notifier &>/dev/null; then
  terminal-notifier \
    -title "Claude Daily Digest" \
    -subtitle "$DATE" \
    -message "$NOTIF_MSG" \
    -sound Glass \
    -open "https://roddy95o.com" \
    -appIcon "https://roddy95o.com/favicon.svg" \
    2>/dev/null
  echo "  Notification: sent via terminal-notifier" >> "$LOG"
else
  # Fallback to osascript (only works in GUI context)
  osascript -e "display notification \"$NOTIF_MSG\" with title \"Claude Daily Digest\" subtitle \"$DATE\" sound name \"Glass\"" 2>/dev/null || true
  echo "  Notification: attempted via osascript" >> "$LOG"
fi

echo "=== [$DATE $TIME] Done ===" >> "$LOG"
